### OBTENER TODOS LOS AUTORES
GET http://localhost:3000/authors
###------------------------------------------
### OBTENER AUTOR POR ID
GET http://localhost:3000/authors/10
###------------------------------------------
### CREAR AUTOR
POST http://localhost:3000/authors/
Content-Type: application/json

{
    "author_name": "Toffito",
    "dato-que-no-se-guarda": "not-found"
}
###------------------------------------------
### ELIMINAR AUTOR
DELETE http://localhost:3000/authors/9
###------------------------------------------
### EDITAR AUTOR
PATCH http://localhost:3000/authors/10
Content-Type: application/json

{
    "author_name": "Capricho"
}
###------------------------------------------

###===============================================================================

### OBTENER TODOS LOS GÉNEROS
GET http://localhost:3000/genres
###------------------------------------------
### OBTENER GÉNERO POR ID
GET http://localhost:3000/genres/4
###------------------------------------------
### CREAR GÉNERO
POST http://localhost:3000/genres/
Content-Type: application/json

{
    "genre": "Horror",
    "dato-que-no-se-guarda": "not-found"
}
###------------------------------------------
### ELIMINAR AUTOR
DELETE http://localhost:3000/genres/6
###------------------------------------------
### EDITAR AUTOR
PATCH http://localhost:3000/genres/3
Content-Type: application/json

{
    "genre": "Sci-Fi"
}
###------------------------------------------

###===============================================================================

### OBTENER TODOS LOS LIBROS
GET http://localhost:3000/books
###------------------------------------------
### OBTENER LIBRO POR ID
GET http://localhost:3000/books/1
###------------------------------------------
### CREAR LIBRO
POST http://localhost:3000/books/
Content-Type: application/json

{
    "title": "Luna de Plutón",
    "book_desc": "Fantasía en la luna y hay un tren y una gigante y un duende y otras weás no sé no lo terminé xD",
    "image_url": "aimayen",
    "author_id": 2,
    "genre_id": 4,
    "dato-que-no-se-guarda": "not-found"
}
###------------------------------------------
### ELIMINAR LIBRO
DELETE http://localhost:3000/books/10
###------------------------------------------
### EDITAR LIBRO
PATCH http://localhost:3000/books/1
Content-Type: application/json

{
    "title": "Cien años de soledad"
}
###------------------------------------------
